# Generated by Django 4.1.6 on 2023-02-16 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0002_atendente_helper_delete_funcionario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.CharField(max_length=30)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_agendada', models.DateTimeField()),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('R', 'Realizado'), ('C', 'Cancelado')], default='P', max_length=1)),
                ('atendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.atendente')),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.helper')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atendimentos.servico')),
            ],
        ),
    ]
