# Generated by Django 4.1.6 on 2023-02-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='fone_cliente',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atendimento',
            name='nome_cliente',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
