# Generated by Django 4.1.6 on 2023-02-16 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0002_atendimento_fone_cliente_atendimento_nome_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='data_cadastro',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
