# Generated by Django 4.1.6 on 2023-02-18 21:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0003_alter_atendimento_data_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='data_agendada',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='data_cadastro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
