# Generated by Django 4.1.6 on 2023-02-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('G', 'Gerente'), ('A', 'Atendente'), ('H', 'Recusado')], default='A', max_length=2)),
            ],
        ),
    ]
