# Generated by Django 4.1.6 on 2023-02-16 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_atendente_helper_delete_funcionario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helper',
            name='senha',
        ),
    ]
